### PR TITLE
Rework plugin structure to replace pluggable with a xml file

### LINKED ISSUE #20: Enhance plugin create task
The plugin creation sbt task (sbt create) should also generate the future metadata file and the class file. This should be implemented after the plugin structure rework.

See: https://github.com/codeoverflow-org/chatoverflow/blob/2cde2f93003bf007d1f6cfd6c509c3922ae620c8/project/BuildUtility.scala#L150

This should be solved before: https://github.com/codeoverflow-org/chatoverflow/issues/41

### PR DESCRIPTION
**Pull request by hlxid**
Implements everything discussed in #41.

Todos:
- [x] Implement PluginLoader to load plugins with the new plugin.xml in every jar. Reach metadata parity with pluggable.
- [x] Remove pluggable from the api (https://github.com/codeoverflow-org/chatoverflow-api/pull/11)
- [x] Add new optional properties to PluginType that pluggable didn't had like `version` and `website`
- [x] Add plugin.xml files to the official plugin repo (https://github.com/codeoverflow-org/chatoverflow-plugins/pull/1)
- [x] Enhance sbt create task (Closes #20)
  - [x] to autogenerate the plugin.xml
  - [x] to autogenerate the class implementing PluginImpl in java/scala.
- [x] Rework sbt fetch task to only fetch plugins with a existing plugin.xml file
- [x] Add new properties to rest api
- [x] Update the wiki to reflect these changes (https://github.com/codeoverflow-org/chatoverflow-wiki/pull/3)

### CODE REVIEW

**Comment by hlxid** [comment]
@sebinside this is now ready to be reviewed :smiley:

**Comment by sebinside** [comment]
Wow, this is huge - thank you! Although I followed the development progress... this might take some while :)

**Comment by hlxid** [comment]
No worries, it doesn't need to done within a certain time. Do it at your pace. :)

**Review by sebinside — APPROVED** [review]
Everything is fine, will be merged soon.

**Comment by sebinside** [comment]
Update npm package to version 0.3.4 with the new plugin metadata. https://www.npmjs.com/package/chatoverflow-api

**Pull request merged**
