### PR TITLE
Support JCenter in Bootstrap Launcher

### PR DESCRIPTION
**Pull request by hlxid**
The Bootstrap Launcher was designed to download anything from Maven Central. 

But since commit 97e67cb has added JDA for Discord the Bootstrap Launcher was not able to download it because it along with some of its dependencies are only hosted on JCenter. 

This pr adds the ability to resolve dependencies from other repos, but currently only JCenter and Maven Central are used. It still tries to get anything from Maven Central and only uses JCenter, or any other repo that may be used in the future, when Maven Central doesn't have a dependency.

Any feedback would be appreciated.

### CODE REVIEW

**Comment by hlxid** [comment]
Is `bootstrap/src/main/resources/dependencies.xml` intended to be commited?

**Comment by sebinside** [comment]
Great pull request, thank you! dependencies.xml ist not ment to be commited. It would be even better to get the output of `sbt dependenciesList` directly, but we were not able to do this without external make file.

I will inspect your changes as soon as possible.

**Comment by hlxid** [comment]
I've managed to get the dependencies directly from sbt. See my latest commit.

**Comment by sebinside** [comment]
Great work! Tested your code, everything works fine and is well developed. Thank you for your help, we would love to welcome you on the code overflow discord server!

**Comment by hlxid** [comment]
No problem. Love how Chat Overflow progresses, as Code Overflow 1 was my main impuls to learn coding.

**Pull request merged**
