### PR TITLE
Add gui to the build process

### PR DESCRIPTION
**Pull request by hlxid**
Adds a task to sbt to build the gui and add it to the classpath. Jetty then serves the gui right from the classpath/jar. Meant to be a transition til the gui is packaged as a electron app.

Currently the gui is included in the jar of the main framework when deployed. Do you rather want it to be in a seperate jar only for the gui or is it fine in the main jar?

### CODE REVIEW

**Comment by sebinside** [comment]
Thank you for this great idea! Until we have a standalone app (way in the future), this is a good solution.

While testing the code, I ran into two problems:
- First, the (updated) custom intellij run configurations do not work properly, since the rely on the GUI-sbt-command, which has to be shared, too (checkbox in the upper right corner of the configuration)
- I was not able to execute the gui sbt command in the IntelliJ windows sbt console, since npm could not be found, although it is abviously in the system path variable. I probably could fix this problem by injecting the npm path into the (missing) sbt gui run configuration mentioned above, but it would not fix the problem for other users. the error message is: `java.io.IOException: Cannot run program "npm" (in directory "gui"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden`. Note, that this seems not to be yours but rather an IntelliJ problem (just google the error message). But we should still provide an alternative approach / solution for this...

**Comment by sebinside** [comment]
See e.g. https://stackoverflow.com/questions/46159276/failed-to-running-command-line-in-java-using-commons-exec-when-trigger-gradle-te/47245725

**Comment by hlxid** [comment]
@sebinside you can now test again. The solution was to execute npm through cmd to get access to the path.

**Comment by sebinside** [comment]
Now everything works fine. Successfully tested on windows and mac os. Thank you!

**Pull request merged**
